
apiVersion: v1
data:
  axis2.xml: |
    <axisconfig name="AxisJava2.0">
        <parameter name="hotdeployment" locked="false">true</parameter>
        <parameter name="hotupdate" locked="false">true</parameter>
        <parameter name="enableMTOM" locked="false">false</parameter>
        <parameter name="enableSwA" locked="false">false</parameter>
        <parameter name="cacheAttachments" locked="false">false</parameter>
        <parameter name="attachmentDIR" locked="false">work/mtom</parameter>
        <parameter name="sizeThreshold" locked="false">4000</parameter>
        <parameter name="disableREST" locked="false">false</parameter>
        <parameter name="Sandesha2StorageManager" locked="false">inmemory</parameter>
        <parameter name="servicePath" locked="false">services</parameter>
        <parameter name="ServicesDirectory">axis2services</parameter>
        <parameter name="httpContentNegotiation">false</parameter>
        <parameter name="ModulesDirectory">axis2modules</parameter>
        <parameter name="userAgent" locked="true">WSO2 EI 6.5.0</parameter>
        <parameter name="server" locked="true">WSO2 EI 6.5.0</parameter>
        <parameter name="sendStacktraceDetailsWithFaults" locked="false">false</parameter>
        <parameter name="DrillDownToRootCauseForFaultReason" locked="false">false</parameter>
        <parameter name="manageTransportSession">true</parameter>
        <parameter name="ConfigContextTimeoutInterval" locked="false">30000</parameter>
        <parameter name="SynapseConfig.ConfigurationFile" locked="false">repository/deployment/server/synapse-configs</parameter>
        <parameter name="SynapseConfig.HomeDirectory" locked="false">.</parameter>
        <parameter name="SynapseConfig.ResolveRoot" locked="false">.</parameter>
        <parameter name="SynapseConfig.ServerName" locked="false">localhost</parameter>
        <parameter name="enableBasicAuth" locked="false">true</parameter>
        <listener class="org.wso2.carbon.core.deployment.DeploymentInterceptor"/>
        <messageReceivers>
            <messageReceiver mep="http://www.w3.org/ns/wsdl/in-only"
                             class="org.apache.axis2.rpc.receivers.RPCInOnlyMessageReceiver"/>
            <messageReceiver mep="http://www.w3.org/ns/wsdl/robust-in-only"
                             class="org.apache.axis2.rpc.receivers.RPCInOnlyMessageReceiver"/>
            <messageReceiver mep="http://www.w3.org/ns/wsdl/in-out"
                             class="org.apache.axis2.rpc.receivers.RPCMessageReceiver"/>
        </messageReceivers>
       <messageFormatters>
            <messageFormatter contentType="application/x-www-form-urlencoded"
                              class="org.apache.synapse.commons.formatters.XFormURLEncodedFormatter"/>
            <messageFormatter contentType="multipart/form-data"
                              class="org.apache.axis2.transport.http.MultipartFormDataFormatter"/>
            <messageFormatter contentType="application/xml"
                              class="org.apache.axis2.transport.http.ApplicationXMLFormatter"/>
            <messageFormatter contentType="text/xml"
                             class="org.apache.axis2.transport.http.SOAPMessageFormatter"/>
            <messageFormatter contentType="application/soap+xml"
                             class="org.apache.axis2.transport.http.SOAPMessageFormatter"/>
            <messageFormatter contentType="text/plain"
                             class="org.apache.axis2.format.PlainTextFormatter"/>
            <messageFormatter contentType="application/octet-stream"
                              class="org.wso2.carbon.relay.ExpandingMessageFormatter"/>
            <messageFormatter contentType="application/json"
                              class="org.wso2.carbon.integrator.core.json.JsonStreamFormatter"/>
        </messageFormatters>
        <messageBuilders>
            <messageBuilder contentType="application/xml"
                            class="org.apache.axis2.builder.ApplicationXMLBuilder"/>
            <messageBuilder contentType="application/x-www-form-urlencoded"
                            class="org.apache.synapse.commons.builders.XFormURLEncodedBuilder"/>
            <messageBuilder contentType="multipart/form-data"
                            class="org.apache.axis2.builder.MultipartFormDataBuilder"/>
            <messageBuilder contentType="text/plain"
                            class="org.apache.axis2.format.PlainTextBuilder"/>
            <messageBuilder contentType="application/octet-stream"
                            class="org.wso2.carbon.relay.BinaryRelayBuilder"/>
            <messageBuilder contentType="application/json"
                            class="org.wso2.carbon.integrator.core.json.JsonStreamBuilder"/>
        </messageBuilders>
         <transportReceiver name="http" class="org.apache.synapse.transport.passthru.PassThroughHttpListener">
            <parameter name="port" locked="false">8280</parameter>
            <parameter name="non-blocking" locked="false">true</parameter>
            <parameter name="WSDLEPRPrefix" locked="false">"ip.node.k8s.&.wso2.ei":30280</parameter>
            <parameter name="httpGetProcessor" locked="false">org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor</parameter>
        </transportReceiver>
         <transportReceiver name="https" class="org.apache.synapse.transport.passthru.PassThroughHttpSSLListener">
            <parameter name="port" locked="false">8243</parameter>
            <parameter name="non-blocking" locked="false">true</parameter>
            <parameter name="HttpsProtocols">TLSv1,TLSv1.1,TLSv1.2</parameter>
            <parameter name="WSDLEPRPrefix" locked="false">"ip.node.k8s.&.wso2.ei":"$nodeport.k8s.&.2.wso2ei"</parameter>
            <parameter name="httpGetProcessor" locked="false">org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor</parameter>
            <parameter name="keystore" locked="false">
                <KeyStore>
                    <Location>repository/resources/security/wso2carbon.jks</Location>
                    <Type>JKS</Type>
                    <Password>wso2carbon</Password>
                    <KeyPassword>wso2carbon</KeyPassword>
                </KeyStore>
            </parameter>
            <parameter name="truststore" locked="false">
                <TrustStore>
                    <Location>repository/resources/security/client-truststore.jks</Location>
                    <Type>JKS</Type>
                    <Password>wso2carbon</Password>
                </TrustStore>
            </parameter>
        </transportReceiver>
        <transportReceiver name="local" class="org.wso2.carbon.core.transports.local.CarbonLocalTransportReceiver"/>
        <transportReceiver name="vfs" class="org.apache.synapse.transport.vfs.VFSTransportListener"/>

        <transportSender name="http" class="org.apache.synapse.transport.passthru.PassThroughHttpSender">
            <parameter name="non-blocking" locked="false">true</parameter>
        </transportSender>
        <transportSender name="https" class="org.apache.synapse.transport.passthru.PassThroughHttpSSLSender">
            <parameter name="non-blocking" locked="false">true</parameter>
            <parameter name="keystore" locked="false">
                <KeyStore>
                    <Location>repository/resources/security/wso2carbon.jks</Location>
                    <Type>JKS</Type>
                    <Password>wso2carbon</Password>
                    <KeyPassword>wso2carbon</KeyPassword>
                </KeyStore>
            </parameter>
            <parameter name="truststore" locked="false">
                <TrustStore>
                    <Location>repository/resources/security/client-truststore.jks</Location>
                    <Type>JKS</Type>
                    <Password>wso2carbon</Password>
                </TrustStore>
            </parameter>
        </transportSender>
        <transportSender name="local" class="org.wso2.carbon.core.transports.local.CarbonLocalTransportSender"/>
        <transportSender name="vfs" class="org.apache.synapse.transport.vfs.VFSTransportSender"/>

        <module ref="addressing"/>
        <clustering class="org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent"
                    enable="false">
            <parameter name="clusteringPattern">nonWorkerManager</parameter>
            <parameter name="AvoidInitiation">true</parameter>
            <parameter name="membershipScheme">wka</parameter>
            <parameter name="membershipScheme">kubernetes</parameter>
            <parameter name="domain">wso2.carbon.domain</parameter>
            <parameter name="domain">wso2.ei.domain</parameter>
            <parameter name="mcastPort">45564</parameter>
            <parameter name="mcastTTL">100</parameter>
            <parameter name="mcastTimeout">60</parameter>
            <parameter name="localMemberHost">127.0.0.1</parameter>
             <parameter name="localMemberHost">integrator</parameter>
            <parameter name="localMemberPort">4100</parameter>
            <parameter name="properties">
                <property name="backendServerURL" value="https://${hostName}:${httpsPort}/services/"/>
                <property name="mgtConsoleURL" value="https://${hostName}:${httpsPort}/"/>
            </parameter>
            <members>
                <member>
                    <hostName>127.0.0.1</hostName>
                    <port>4000</port>
                </member>
            </members>
            <parameter name="membershipSchemeClassName">org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme</parameter>
            <parameter name="KUBERNETES_NAMESPACE">wso2</parameter>
            <parameter name="KUBERNETES_SERVICES">wso2ei-integrator-service</parameter>
            <parameter name="KUBERNETES_MASTER_SKIP_SSL_VERIFICATION">true</parameter>
            <parameter name="USE_DNS">false</parameter>
            <groupManagement enable="false">
                <applicationDomain name="wso2.esb.domain"
                                   description="EI group"
                                   agent="org.wso2.carbon.core.clustering.hazelcast.HazelcastGroupManagementAgent"
                                   subDomain="worker"
                                   port="2222"/>
            </groupManagement>
        </clustering>
        <phaseOrder type="InFlow">
            <phase name="MsgInObservation">
    	    <handler name="TraceMessageBuilderDispatchHandler"
                         class="org.apache.synapse.transport.passthru.util.TraceMessageBuilderDispatchHandler"/>
    	</phase>
            <phase name="Validation"/>
            <phase name="Transport">
                <handler name="IntegratorStatefulHandler" class="org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler">
                    <order phase="Transport"/>
                    <handler name="JSONMessageHandler"
                             class="org.apache.axis2.json.gson.JSONMessageHandler" />
                </handler>
       	        <handler name="CarbonContextConfigurator"
                         class="org.wso2.carbon.mediation.initializer.handler.CarbonContextConfigurator"/>
                <handler name="RelaySecuirtyMessageBuilderDispatchandler"
                         class="org.apache.synapse.transport.passthru.util.RelaySecuirtyMessageBuilderDispatchandler"/>
                <handler name="SOAPActionBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPActionBasedDispatcher">
                    <order phase="Transport"/>
                </handler>
            </phase>
            <phase name="Addressing">
                <handler name="AddressingBasedDispatcher"
                         class="org.apache.axis2.dispatchers.AddressingBasedDispatcher">
                    <order phase="Addressing"/>
                </handler>
            </phase>
            <phase name="Security"/>
            <phase name="PreDispatch">
            </phase>
            <phase name="Dispatch" class="org.apache.axis2.engine.DispatchPhase">
                <handler name="IntegratorStatefulHandler" class="org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler"/>
                <handler name="JSONMessageHandler" class="org.apache.axis2.json.gson.JSONMessageHandler" />
                <handler name="SOAPActionBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"/>
                <handler name="RequestURIOperationDispatcher"
                         class="org.apache.axis2.dispatchers.RequestURIOperationDispatcher"/>
                <handler name="SOAPMessageBodyBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPMessageBodyBasedDispatcher"/>
                <handler name="HTTPLocationBasedDispatcher"
                         class="org.apache.axis2.dispatchers.HTTPLocationBasedDispatcher"/>
                <handler name="MultitenantDispatcher"
                         class="org.wso2.carbon.tenant.dispatcher.MultitenantDispatcher"/>
                <handler name="SynapseDispatcher"
                         class="org.apache.synapse.core.axis2.SynapseDispatcher"/>
                <handler name="SynapseMustUnderstandHandler"
                         class="org.apache.synapse.core.axis2.SynapseMustUnderstandHandler"/>
            </phase>
            <phase name="RMPhase"/>
            <phase name="OpPhase"/>
            <phase name="AuthPhase"/>
            <phase name="MUPhase"/>
            <phase name="OperationInPhase"/>
        </phaseOrder>
        <phaseOrder type="OutFlow">
            <phase name="UEPPhase" />
            <phase name="RMPhase"/>
            <phase name="MUPhase"/>
            <phase name="OpPhase"/>
            <phase name="OperationOutPhase"/>
            <phase name="PolicyDetermination"/>
            <phase name="PTSecurityOutPhase">
    		<handler name="RelaySecuirtyMessageBuilderDispatchandler"
                         class="org.apache.synapse.transport.passthru.util.RelaySecuirtyMessageBuilderDispatchandler"/>
    	    </phase>
            <phase name="MessageOut"/>
            <phase name="Security"/>
            <phase name="MsgOutObservation"/>
        </phaseOrder>
        <phaseOrder type="InFaultFlow">
            <phase name="MsgInObservation"/>
            <phase name="Validation"/>
            <phase name="Transport">
                <handler name="IntegratorStatefulHandler" class="org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler">
                    <order phase="Transport"/>
                    <handler name="JSONMessageHandler"
                             class="org.apache.axis2.json.gson.JSONMessageHandler" />
                </handler>
                <handler name="SOAPActionBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPActionBasedDispatcher">
                    <order phase="Transport"/>
                </handler>
            </phase>
            <phase name="Addressing">
                <handler name="AddressingBasedDispatcher"
                         class="org.apache.axis2.dispatchers.AddressingBasedDispatcher">
                    <order phase="Addressing"/>
                </handler>
            </phase>
            <phase name="Security"/>
            <phase name="PreDispatch"/>
            <phase name="Dispatch" class="org.apache.axis2.engine.DispatchPhase">
                <handler name="IntegratorStatefulHandler" class="org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler"/>
                <handler name="SOAPActionBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"/>
                <handler name="RequestURIOperationDispatcher"
                         class="org.apache.axis2.dispatchers.RequestURIOperationDispatcher"/>
                <handler name="SOAPMessageBodyBasedDispatcher"
                         class="org.apache.axis2.dispatchers.SOAPMessageBodyBasedDispatcher"/>
                <handler name="HTTPLocationBasedDispatcher"
                         class="org.apache.axis2.dispatchers.HTTPLocationBasedDispatcher"/>
            </phase>
            <phase name="RMPhase"/>
            <phase name="OpPhase"/>
            <phase name="MUPhase"/>
            <phase name="OperationInFaultPhase"/>
        </phaseOrder>
        <phaseOrder type="OutFaultFlow">
            <phase name="UEPPhase" />
            <phase name="RMPhase"/>
            <phase name="MUPhase"/>
            <phase name="OperationOutFaultPhase"/>
            <phase name="PolicyDetermination"/>
            <phase name="MessageOut"/>
            <phase name="Security"/>
    	<phase name="Transport"/>
            <phase name="MsgOutObservation"/>
        </phaseOrder>
    </axisconfig>
kind: ConfigMap
metadata:
  name: integrator-conf-axis2
  namespace: "$ns.k8s&wso2.ei"
---
